version: '3'

networks:
  laravel:

volumes:
  mysql-data:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env.docker
    environment:
      - MYSQL_DATABASE="${DB_DATABASE}"
      - MYSQL_USER="${DB_USERNAME}"
      - MYSQL_PASSWORD="${DB_PASSWORD}"
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - laravel

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - "8025:80"
    networks:
      - laravel

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    env_file:
      - .env.docker
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    env_file:
      - .env.docker
    networks:
      - laravel
