version: "3"

networks:
  backend:

volumes:
  mysql-data:
  app-data:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - app-data:/var/www/html
      - ../nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chatbot
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env.prod
    environment:
      - MYSQL_DATABASE="${DB_DATABASE:-}"
      - MYSQL_USER="${DB_USERNAME:-}"
      - MYSQL_PASSWORD="${DB_PASSWORD:-}"
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - SERVICE_TAGS=prod
      - SERVICE_NAME=mysql

    networks:
      - backend

  chatbot:
    image: goteo/chatbot:0.3
    container_name: chatbot
    depends_on:
      - mysql
    volumes:
      - app-data:/var/www/html
    #   - ./entrypoint.sh:/entrypoint
    # entrypoint: /entrypoint
    # command: php-fpm
    env_file:
      - .env.prod
    environment:
      - LOG_CHANNEL=stderr
    networks:
      - backend


